### ISSUE TITLE
grunt build Failure

### ISSUE THREAD

**Issue by James-Gallagher** [buttercup-pw/buttercup#77]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/grunt", line 9, in <module>
    load_entry_point('grunt==0.1.1', 'console_scripts', 'grunt')()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/grunt/render.py", line 94, in main
    render_from_file(**options)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/grunt/render.py", line 54, in render_from_file
    with codecs.open(input, encoding=encoding) as f:
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py", line 884, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 2] No such file or directory: 'build'

**Comment by perry-mitchell** [comment]
This currently does not look like an issue with our setup.

Could you reply with your node/npm versions, OS, and the exact command you ran?

**Comment by perry-mitchell** [comment]
Closing due to no activity.
